dist: trusty
sudo: required
language:
  - cpp
compiler:
  - gcc
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-6
      - g++-6
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl2-dev
script:
  - gcc -v && g++ -v && cmake --version
  # Run your build commands next
  - make
